spring.application.name=commerce
# Perfil padrão para desenvolvimento local
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Configurações globais que não dependem do profile
spring.jpa.open-in-view=false
